/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurants;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashish
 */
public class EmployeeDetails extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form EmployeeDetails
     */
    public EmployeeDetails() {
        initComponents();
        setLocationRelativeTo(null);
        SearchButton.addActionListener(this);
        EditUser.addActionListener(this);
        UpdateUser.addActionListener(this);
        DeleteUser.addActionListener(this);
        EmNameField.setEditable(false);
        EmPermAdd.setEditable(false);
        EmPermAdd.setEditable(false);
        EmPhone.setEditable(false);
        EmVIDNo.setEditable(false);
        EmType.setEditable(false);
    }

    public void SetEmDetails(String Name, String PermAddrress, String PreAddrress, String Phone, String VID, String Type) {
        System.out.println("Employee Name: " + Name);
        EmNameField.setText(Name);
        EmPermAdd.setText(PermAddrress);
        EmPreAdd.setText(PreAddrress);
        EmPhone.setText(Phone);
        EmVIDNo.setText(VID);
        EmType.setText(Type);

        //System.out.println("Bujhlam na kicchu! :( ");
    }
    public void showUpdateMessege(){
        this.setVisible(true);
        EmNameField.setText("");
        EmPermAdd.setText("");
        EmPreAdd.setText("");
        EmPhone.setText("");
        EmVIDNo.setText("");
        EmType.setText("");
        JOptionPane.showMessageDialog(null, "User Details Updated Successfully!");
        
    }
    int ID;
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(SearchButton)) {
            String id = IDField.getText();
            //String name = NameField.getText();
            ID = Integer.parseInt(IDField.getText());
            try {
                DataBase db = new DataBase();
                db.SearchEmployee(id);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(EmployeeDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (e.getSource().equals(EditUser)) {
            EmNameField.setEditable(true);
            EmPermAdd.setEditable(true);
            EmPermAdd.setEditable(true);
            EmPhone.setEditable(true);
            EmVIDNo.setEditable(true);
            EmType.setEditable(true);
        }
        if (e.getSource().equals(UpdateUser)) {
            //ID = Integer.parseInt(IDField.getText());
            String name = EmNameField.getText();
            String add1 = EmPermAdd.getText();
            String add2 = EmPermAdd.getText();
            String phone = EmPhone.getText();
            String vidNo = EmVIDNo.getText();
            String type = EmType.getText();
            try {
                DataBase db = new DataBase();
                db.UpdateEmployee(ID, name, add1, add2, phone, vidNo, type);
                //this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(EmployeeDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        PrintButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        AdminUserName3 = new javax.swing.JLabel();
        AdminUserName4 = new javax.swing.JLabel();
        AdminUserName5 = new javax.swing.JLabel();
        AdminUserName6 = new javax.swing.JLabel();
        AdminUserName7 = new javax.swing.JLabel();
        AdminUserName8 = new javax.swing.JLabel();
        AdminUserName9 = new javax.swing.JLabel();
        DeleteUser = new javax.swing.JButton();
        UpdateUser = new javax.swing.JButton();
        EditUser = new javax.swing.JButton();
        EmNameField = new javax.swing.JTextField();
        EmPhone = new javax.swing.JTextField();
        EmVIDNo = new javax.swing.JTextField();
        EmType = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmPermAdd = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        EmPreAdd = new javax.swing.JTextArea();
        AdminUserName2 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 4));

        PrintButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        PrintButton.setForeground(new java.awt.Color(0, 0, 153));
        PrintButton.setText("Print");

        HomeButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(0, 0, 153));
        HomeButton.setText("Home");

        AdminUserName3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        AdminUserName3.setText("Employee Name   :");

        AdminUserName4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        AdminUserName4.setText("Addrress");

        AdminUserName5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        AdminUserName5.setText("Permanent       :");

        AdminUserName6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        AdminUserName6.setText("Present         :");

        AdminUserName7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        AdminUserName7.setText("Voter ID No     :");

        AdminUserName8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        AdminUserName8.setText("Phone No        :");

        AdminUserName9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        AdminUserName9.setText("Employee Type   :");

        DeleteUser.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        DeleteUser.setForeground(new java.awt.Color(0, 0, 153));
        DeleteUser.setText("Delete");

        UpdateUser.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        UpdateUser.setForeground(new java.awt.Color(0, 0, 153));
        UpdateUser.setText("Update");

        EditUser.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        EditUser.setForeground(new java.awt.Color(0, 0, 153));
        EditUser.setText("Edit");

        EmNameField.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        EmNameField.setForeground(new java.awt.Color(0, 0, 204));

        EmPhone.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        EmPhone.setForeground(new java.awt.Color(0, 0, 204));

        EmVIDNo.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        EmVIDNo.setForeground(new java.awt.Color(0, 0, 204));

        EmType.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        EmType.setForeground(new java.awt.Color(0, 0, 204));

        EmPermAdd.setColumns(20);
        EmPermAdd.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        EmPermAdd.setForeground(new java.awt.Color(0, 0, 153));
        EmPermAdd.setRows(5);
        jScrollPane1.setViewportView(EmPermAdd);

        EmPreAdd.setColumns(20);
        EmPreAdd.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        EmPreAdd.setForeground(new java.awt.Color(0, 0, 153));
        EmPreAdd.setRows(5);
        jScrollPane2.setViewportView(EmPreAdd);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(PrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                        .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminUserName4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminUserName8, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(AdminUserName7, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(AdminUserName9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminUserName5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AdminUserName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(EditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EmNameField)
                            .addComponent(EmPhone)
                            .addComponent(EmVIDNo)
                            .addComponent(EmType)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(AdminUserName6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmNameField)
                    .addComponent(AdminUserName3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(AdminUserName4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdminUserName5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminUserName6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminUserName8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmPhone))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminUserName7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmVIDNo))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminUserName9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmType))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        AdminUserName2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        AdminUserName2.setText("Search User :");

        IDField.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel8.setText("ID");

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Employee Details");

        SearchButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(0, 0, 153));
        SearchButton.setText("Search");

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(AdminUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(108, 108, 108))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDField)
                    .addComponent(AdminUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminUserName2;
    private javax.swing.JLabel AdminUserName3;
    private javax.swing.JLabel AdminUserName4;
    private javax.swing.JLabel AdminUserName5;
    private javax.swing.JLabel AdminUserName6;
    private javax.swing.JLabel AdminUserName7;
    private javax.swing.JLabel AdminUserName8;
    private javax.swing.JLabel AdminUserName9;
    private javax.swing.JButton DeleteUser;
    private javax.swing.JButton EditUser;
    private javax.swing.JTextField EmNameField;
    private javax.swing.JTextArea EmPermAdd;
    private javax.swing.JTextField EmPhone;
    private javax.swing.JTextArea EmPreAdd;
    private javax.swing.JTextField EmType;
    private javax.swing.JTextField EmVIDNo;
    private javax.swing.JButton HomeButton;
    private javax.swing.JTextField IDField;
    private javax.swing.JButton PrintButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateUser;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
